# Generated by Django 5.0.3 on 2024-03-31 12:05

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catagory",
            name="icon",
            field=models.FileField(
                blank=True, null=True, upload_to=server.models.Catagory_icon_upload_path
            ),
        ),
    ]
