# Generated by Django 5.0.3 on 2024-03-31 13:22

import server.models
import server.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_catagory_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.server_banner_upload_path,
                validators=[server.validators.validate_image_file_extension],
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.server_icon_upload_path,
                validators=[server.validators.validate_image_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="catagory",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=server.models.Catagory_icon_upload_path,
                validators=[server.validators.validate_image_file_extension],
            ),
        ),
    ]
